# Generated by Django 4.1.7 on 2023-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='foodgram.IngredientQuantity', to='foodgram.ingredient', verbose_name='Игредиенты'),
        ),
    ]
