# Generated by Django 4.1.7 on 2023-02-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'ordering': ('recipe',), 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='quantity',
            new_name='amount',
        ),
    ]
